---
name: Problem Statement
description: Describe a problem statement associated with the Margo Specification that requires a resolution.
labels: "[Problem Statement]"
body:
  - type: markdown
    attributes:
      value: |
        Search [existing issues](https://github.com/margo/specification/labels/Problem%20Statement) before creating a new problem statement
  
  - type: markdown
    attributes:
      value: "## Problem Statement"
  - type: markdown
    attributes:
      value: |
        A problem statement is a special work item for complex issues that can be solved in many ways. The purpose of a problem statement is to solicit feedback from the community on how to solve the problem by documenting proposals instead of only discussing them during weekly calls.
  - type: textarea
    attributes:
      label: "Description"
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: "Associated requirements"
      description: "Link to any requirements this problem statement addresses"
    validations:
      required: false

  - type: dropdown
    attributes:
      label: "Impacted Margo components"
      multiple: true
      options:
        - Application Definition Package
        - Workload Fleet Manager
        - Device Agent
        - Observability
        - Device Fleet Manager
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"
  - type: markdown
    attributes:
      value: "## Proposed Solutions"
  - type: markdown
    attributes:
      value: |
        If anyone has a proposed solution, it must be documented and placed in the location indicated below. Only documented proposals will be considered when evaluating solutions to this problem.
  - type: input
    attributes:
      label: "Location"
      description: "Location for documented proposals"
      placeholder: "[link](link)."
  - type: textarea
    attributes:
      label: "Use cases/scenarios"
      description: "Describe the use cases/scenarios each proposal must address"
      value: | 
        1. 
        2. 
        3. 
        ...
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"
  - type: markdown
    attributes:
      value: "## References"
  - type: textarea
    attributes:
      label: "Reference links"
    validations:
      required: false
