---
name: Business Feature
description: A business feature is a roadmap work item that drives additional functionality/value within the Margo deliverables. Business features are associated with one to many product management child epic(s). 
labels: "[Business Feature]"
body:
  - type: markdown
    attributes:
      value: "## Business Feature"
  - type: markdown
    attributes:
      value: |
        A business feature is a roadmap work item that drives additional functionality/value within the Margo deliverables. Business features are associated with one to many product management child epic(s).
  - type: textarea
    attributes:
      label: "Provide feature description below:"
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: "## Acceptance Criteria"
  - type: textarea
    attributes:
      label: "Provide adequate technical acceptance criteria(s) associated with this feature below:" 
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: "## Feature Use-Cases"
  - type: textarea
    attributes:
      label: "Although not required, it is highly encouraged to provide feature use-cases below:" 
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Additional Feature Information"
  - type: textarea
    attributes:
      label: "Additional information"
      description: "Describe any associated Functional/Non-Functional requirements, technical workflows, or other details to ensure clarity on the goals of the feature."
    validations:
      required: false

