---
name: Technical Feature
description: A technical feature is a roadmap work item that drives additional functionality/value within the Margo deliverables. Technical features may be associated with business features.
labels: "[Technical Feature]"
body:
  - type: markdown
    attributes:
      value: "## Technical Feature"
  - type: markdown
    attributes:
      value: |
         A technical feature is a roadmap work item that drives additional functionality/value within the Margo deliverables. Technical features may be associated with business features. 
  - type: textarea
    attributes:
      label: "Feature description"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Acceptance Criteria"
  - type: textarea
    attributes:
      label: "Provide adequate technical acceptance criteria(s) associated with this feature below:" 
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: "## Feature Use-Cases"
  - type: textarea
    attributes:
      label: "Although not required, it is highly encouraged to provide feature use-cases below:" 
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Additional Feature Information"
  - type: textarea
    attributes:
      label: "Additional information"
      description: "Describe any associated Functional/Non-Functional requirements, technical workflows, or other details to ensure clarity on the goals of the feature."
    validations:
      required: false